export const COMPANY = {
  name: 'Zebracat AI Publicity',
  shortName: 'Zebracat',
  tagline: "India's 360° Media Growth Engine",
  address: 'Sector-72, Fazilpur, Gurugram – 122001',
  addressFull: 'Zebracat AI Publicity, Sector-72, Fazilpur, Gurugram – 122001',
  email: 'info@zebracatindia.com',
  phone: '+91 8882861568',
  phoneRaw: '+918882861568',
  whatsapp: '918882861568',
  whatsappMessage: 'Hi, I\'m interested in advertising with Zebracat. Can you help me plan a campaign?',
  website: 'https://zebracatindia.com',
  mapsUrl: 'https://maps.google.com/?q=Sector-72,Fazilpur,Gurugram,Haryana,122001',
  socials: {
    facebook: 'https://www.facebook.com/zebracatindia',
    twitter: 'https://twitter.com/ZebracatAi',
    instagram: 'https://www.instagram.com/zebracatindia',
    linkedin: 'https://www.linkedin.com/company/zebracat-ai-publicity',
  },
  rating: '4.5',
  reviewCount: '450+',
  stats: {
    mediaManagedCr: '50',
    brands: '1,200+',
    states: '28',
    campaigns: '5,000+',
    deliveryRate: '95%',
  },
}

export const SERVICES = [
  {
    id: 'newspaper',
    name: 'Newspaper Advertising',
    slug: 'newspaper-advertising',
    shortName: 'Newspaper',
    icon: 'newspaper',
    color: '#6F4CF5',
    description: 'Reach millions of readers daily across 500+ publications nationwide.',
    promise: 'Same-day booking in top metros',
    stats: '500+ publications',
    budgetRange: '₹5,000 – ₹50 Lakh',
    heroWord: 'Newspaper Ads',
  },
  {
    id: 'radio',
    name: 'Radio Advertising',
    slug: 'radio-advertising',
    shortName: 'Radio',
    icon: 'radio',
    color: '#22D3EE',
    description: 'Prime-time radio spots on top FM stations — drive recall and footfall.',
    promise: 'Prime-time FM slots guaranteed',
    stats: '200+ radio stations',
    budgetRange: '₹10,000 – ₹20 Lakh',
    heroWord: 'Radio Spots',
  },
  {
    id: 'tv',
    name: 'TV Advertising',
    slug: 'tv-advertising',
    shortName: 'TV',
    icon: 'tv',
    color: '#3B2EE0',
    description: 'Mass-reach TV campaigns on national and regional channels with AI-optimised slots.',
    promise: 'GRP-optimised prime time',
    stats: '300+ channels',
    budgetRange: '₹50,000 – ₹5 Cr+',
    heroWord: 'TV Campaigns',
  },
  {
    id: 'cinema',
    name: 'Cinema PR / Cinema Advertising',
    slug: 'cinema-advertising',
    shortName: 'Cinema',
    icon: 'film',
    color: '#F59E0B',
    description: 'Captivate audiences before the big screen. Cinema advertising that truly lands.',
    promise: 'PVR, INOX, Carnival & more',
    stats: '4,000+ screens',
    budgetRange: '₹25,000 – ₹50 Lakh',
    heroWord: 'Cinema Slots',
  },
  {
    id: 'ott',
    name: 'OTT Advertising / Media Buying',
    slug: 'ott-advertising',
    shortName: 'OTT',
    icon: 'monitor',
    color: '#10B981',
    description: 'Programmatic OTT inventory across Netflix, Hotstar, JioCinema, Sony LIV & more.',
    promise: 'Programmatic OTT inventory',
    stats: '15+ OTT platforms',
    budgetRange: '₹20,000 – ₹2 Cr',
    heroWord: 'OTT Inventory',
  },
  {
    id: 'digital-signage',
    name: 'Digital Signage',
    slug: 'digital-signage',
    shortName: 'LED Screens',
    icon: 'monitor-dot',
    color: '#6F4CF5',
    description: 'LED screens in malls, markets, and retail hubs — real-time dynamic content.',
    promise: 'Real-time content switching',
    stats: '10,000+ LED screens',
    budgetRange: '₹10,000 – ₹25 Lakh',
    heroWord: 'Digital Signage',
  },
  {
    id: 'influencer',
    name: 'Influencer Marketing',
    slug: 'influencer-marketing',
    shortName: 'Influencer',
    icon: 'users',
    color: '#EC4899',
    description: 'Micro to mega influencer campaigns with vetted creators and measurable ROI.',
    promise: 'Performance-tracked campaigns',
    stats: '50,000+ creators',
    budgetRange: '₹15,000 – ₹1 Cr',
    heroWord: 'Influencer Drops',
  },
  {
    id: 'lift-branding',
    name: 'Lift Branding',
    slug: 'lift-branding',
    shortName: 'Lift Branding',
    icon: 'building-2',
    color: '#F97316',
    description: 'Premium lift branding in residential and commercial towers across metro cities.',
    promise: 'Daily impressions, captive audience',
    stats: '25,000+ lifts',
    budgetRange: '₹5,000 – ₹10 Lakh',
    heroWord: 'Lift Branding',
  },
  {
    id: 'transit',
    name: 'Transit Media',
    slug: 'transit-media',
    shortName: 'Transit',
    icon: 'bus',
    color: '#14B8A6',
    description: 'Buses, metros, autos and cabs — moving ads that reach every corner of the city.',
    promise: 'City-wide mobile visibility',
    stats: '1,00,000+ vehicles',
    budgetRange: '₹20,000 – ₹30 Lakh',
    heroWord: 'Transit Ads',
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Ashutosh Rana',
    role: 'Marketing Head',
    company: 'Retail Chain',
    city: 'Gurgaon',
    medium: 'Lift Branding',
    rating: 5,
    text: 'Zebracat delivered exceptional lift branding campaigns across our tower network. The AI-assisted targeting was on point, and the execution was flawless. Our brand recall in the catchment area jumped significantly.',
    avatar: '/images/testimonials/ashutosh-rana.jpg',
  },
  {
    id: 2,
    name: 'Amit Desai',
    role: 'Founder',
    company: 'EdTech Startup',
    city: 'Mumbai',
    medium: 'Newspaper Advertising',
    rating: 5,
    text: 'Within 48 hours, our newspaper ads were live in 12 cities simultaneously. The booking process was seamless, the creative team was brilliant, and the results were measurable. Best media agency we\'ve worked with.',
    avatar: '/images/testimonials/amit-desai.jpg',
  },
  {
    id: 3,
    name: 'Ashish Shrimar',
    role: 'Brand Manager',
    company: 'FMCG Company',
    city: 'Delhi',
    medium: 'Radio Advertising',
    rating: 5,
    text: 'Their radio planning is data-driven like nothing I\'ve seen before. They matched our audience perfectly with FM stations and time slots. CPL dropped by 35% compared to our last campaign.',
    avatar: '/images/testimonials/ashish-shrimar.jpg',
  },
  {
    id: 4,
    name: 'Shubham Sharma',
    role: 'Director',
    company: 'Real Estate Developer',
    city: 'Ratlam',
    medium: 'Digital Signage',
    rating: 5,
    text: 'Zebracat\'s digital signage network in Ratlam helped us generate 300+ site visits in a single week. The LED screen placements were strategic and the content management was effortless.',
    avatar: '/images/testimonials/shubham-sharma.jpg',
  },
  {
    id: 5,
    name: 'Ramesh Garg',
    role: 'CEO',
    company: 'Healthcare Group',
    city: 'Chandigarh',
    medium: 'Transit Media',
    rating: 4,
    text: 'We wanted pan-city visibility in Chandigarh at a reasonable budget. Zebracat\'s transit media solution was perfect — bus branding across 50+ routes gave us incredible reach. Highly recommend.',
    avatar: '/images/testimonials/ramesh-garg.jpg',
  },
  {
    id: 6,
    name: 'Mohit Narang',
    role: 'VP Marketing',
    company: 'D2C Brand',
    city: 'Gurgaon',
    medium: 'OTT Advertising',
    rating: 5,
    text: 'The OTT campaign Zebracat ran for us on Hotstar and JioCinema drove 4x ROAS. Their programmatic team is sharp, and the reporting dashboard was genuinely useful. Will definitely continue.',
    avatar: '/images/testimonials/mohit-narang.jpg',
  },
]

export const NAV_LINKS = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  {
    label: 'Services',
    href: '/services',
    children: SERVICES.map((s) => ({ label: s.name, href: `/services/${s.slug}` })),
  },
  { label: 'Case Studies', href: '/case-studies' },
  { label: 'Pricing', href: '/pricing' },
  { label: 'Blog', href: '/blog' },
  { label: 'ZAP STAR', href: '/zap-star' },
  { label: 'Contact', href: '/contact' },
]

export const ZAP_STAR = {
  name: 'ZAP STAR',
  tagline: 'Powering Your Success – Empowering Retailers, Accelerating Growth Nationwide.',
  description: 'Join the Zebracat partner network and unlock exclusive benefits — co-branded campaigns, marketing support, priority booking, and revenue sharing.',
  benefits: [
    'Co-branded campaign support',
    'Priority booking access',
    'Revenue sharing on referrals',
    'Free creative assistance',
    'Dedicated account manager',
    'Performance dashboard access',
  ],
  // Deck distributed on request — link to a contact form so we can track interest.
  deckUrl: '/contact?subject=zap-star',
}

export const CASE_STUDIES = [
  {
    slug: 'retail-digital-signage-ratlam',
    title: 'Retail Chain Drives 300+ Site Visits via Digital Signage',
    client: 'Shubham Sharma, Real Estate Developer',
    city: 'Ratlam',
    mediums: ['Digital Signage'],
    industry: 'Real Estate',
    results: { reach: '5 Lakh+', leads: '300+', cpl: '₹280' },
    summary: 'Strategic LED screen placements across Ratlam drove 300+ site visits for a residential project launch in a single week.',
    challenge: 'A regional developer was launching a premium residential project in Ratlam with a 14-day pre-launch window and no brand recall in the catchment.',
    solution: 'Zebracat mapped 18 high-footfall LED screens across malls, key junctions and three premium gated communities. Creatives rotated by daypart — morning logo+phone, evening price+QR.',
    outcome: 'In seven days the project recorded 312 site visits attributable to the QR code on the screens. CPL came in at ₹280, roughly 70% lower than the developer\'s benchmark from print.',
  },
  {
    slug: 'edtech-newspaper-12-cities',
    title: 'EdTech Brand Goes Live in 12 Cities in 48 Hours',
    client: 'Amit Desai, EdTech Startup',
    city: 'Mumbai',
    mediums: ['Newspaper Advertising'],
    industry: 'Education',
    results: { reach: '45 Lakh+', signups: '1,200+', roi: '4.2×' },
    summary: 'Zebracat\'s same-day newspaper booking engine launched pan-India ads for an EdTech brand within 48 hours of brief receipt.',
    challenge: 'The brand needed simultaneous quarter-page ads across English and regional dailies in 12 cities ahead of a Saturday admissions deadline. Traditional agencies quoted 7–10 days.',
    solution: 'Zebracat used its inventory API to confirm placements in 14 publications inside 6 hours. Creative was localised for Hindi, Marathi and Tamil overnight.',
    outcome: 'Ads ran in 12 cities within 48 hours. Tracked signups crossed 1,200 in three days, delivering a 4.2x ROAS on the print spend alone.',
  },
  {
    slug: 'healthcare-transit-chandigarh',
    title: 'Healthcare Group Achieves City-Wide Recall via Transit Media',
    client: 'Ramesh Garg, Healthcare Group',
    city: 'Chandigarh',
    mediums: ['Transit Media'],
    industry: 'Healthcare',
    results: { reach: '18 Lakh/week', routesCovered: '50+', brandRecall: '+42%' },
    summary: 'Bus branding across 50+ Chandigarh routes gave a healthcare network city-wide visibility at a fraction of TV costs.',
    challenge: 'A multi-speciality hospital needed mass awareness in Chandigarh\'s tri-city catchment but a TV burst was outside budget.',
    solution: 'Zebracat secured full-wrap branding on 60 buses covering Sectors 1–48 plus Panchkula and Mohali. Creatives focused on the new oncology and cardiology wings.',
    outcome: 'Independent recall surveys showed unaided awareness of the hospital brand rose 42 percentage points over the four-week burst.',
  },
  {
    slug: 'fmcg-radio-campaign',
    title: 'FMCG Brand Cuts CPL by 35% with AI-Optimised Radio Slots',
    client: 'Ashish Shrimar, FMCG Company',
    city: 'Delhi',
    mediums: ['Radio Advertising'],
    industry: 'FMCG',
    results: { stations: '8', duration: '4 weeks', cplReduction: '35%' },
    summary: 'AI-driven radio station and slot selection reduced CPL by 35% for an FMCG product launch across Delhi NCR.',
    challenge: 'A snack brand had run radio for years with flat CPL. Leadership wanted a measurable step-change before a national rollout.',
    solution: 'Zebracat\'s planning AI matched the target persona (25-44, female, head of household) against the listenership of eight FM stations and reallocated the budget toward morning drive on three stations that over-indexed.',
    outcome: 'CPL fell 35% vs the prior campaign, and post-burst brand search lifted 1.8x.',
  },
  {
    slug: 'lift-branding-d2c',
    title: 'D2C Brand Builds Neighbourhood Presence via Lift Branding',
    client: 'Mohit Narang, D2C Brand',
    city: 'Gurgaon',
    mediums: ['Lift Branding', 'OTT Advertising'],
    industry: 'Consumer / D2C',
    results: { lifts: '800+', impressionsPerDay: '40,000+', roas: '4×' },
    summary: 'Combined lift branding in Gurgaon towers with OTT retargeting created a surround-sound effect for a D2C brand launch.',
    challenge: 'A premium personal-care D2C wanted to seed its launch in Gurgaon\'s high-income towers and convert via app installs.',
    solution: 'Lift branding in 850+ lifts across DLF and Sohna Road towers, paired with geo-fenced retargeting on Hotstar and JioCinema using the same creative codes.',
    outcome: '4x ROAS on tracked installs, with the brand seeing a 3.4x lift in unaided recall inside the geo-fenced towers vs control sites.',
  },
  {
    slug: 'retail-lift-branding-gurgaon',
    title: 'Retail Chain Sees Brand Recall Jump in Catchment Area',
    client: 'Ashutosh Rana, Marketing Head',
    city: 'Gurgaon',
    mediums: ['Lift Branding'],
    industry: 'Retail',
    results: { towersTargeted: '150+', residents: '60,000+', recallLift: '+55%' },
    summary: 'Precision lift branding across 150+ Gurgaon residential towers drove a 55% brand recall uplift in the target catchment.',
    challenge: 'A retail chain was opening a flagship store in Sector 29 and needed to dominate the 3 km catchment in four weeks.',
    solution: 'Zebracat mapped 153 towers within a 3 km radius and ran branded lift panels with weekly creative refreshes tied to in-store offers.',
    outcome: 'Footfall in the launch month was 38% above the chain\'s previous flagship benchmark; recall climbed 55 percentage points.',
  },
] as const

export const FAQS = [
  {
    category: 'Booking',
    question: 'How quickly can I book an ad campaign with Zebracat?',
    answer: 'Most campaigns can be booked and live within 24–48 hours for digital and OTT. Newspaper and radio can often go live same-day in metro cities. Cinema and transit may need 3–5 business days for production and deployment.',
  },
  {
    category: 'Booking',
    question: 'Can I book ads across multiple cities in one go?',
    answer: 'Absolutely. Our multi-city booking engine lets you select locations, publications, stations and screens across all 28 states simultaneously. You get a unified dashboard and single invoice.',
  },
  {
    category: 'Payments',
    question: 'What payment options do you accept?',
    answer: 'We accept UPI, NEFT/RTGS, credit/debit cards, and Razorpay payment links. GST invoices are provided for all transactions. Installment options are available for campaigns above ₹5 Lakh.',
  },
  {
    category: 'Creative',
    question: 'Do you help with ad creative and design?',
    answer: 'Yes! Our AI Creative Studio can generate newspaper copy, radio scripts, TV storyboard outlines, and influencer briefs. We also have an in-house creative team for full production services.',
  },
  {
    category: 'Creative',
    question: 'What file formats do you accept for ad creatives?',
    answer: 'We accept PDF, AI, PSD, EPS for print. MP4/MOV for video (H.264 or H.265). JPG/PNG for digital displays. Radio: MP3 at minimum 256kbps. Our team can also convert and adapt formats.',
  },
  {
    category: 'Reporting',
    question: 'How do I track my campaign performance?',
    answer: 'Every campaign gets a real-time dashboard showing impressions, reach, GRP (for TV/Radio), CPM, top-performing cities and time slots. You receive weekly automated reports and a final wrap-up deck.',
  },
  {
    category: 'Reporting',
    question: 'What data and analytics do you provide post-campaign?',
    answer: 'Post-campaign reports include: total reach & impressions, frequency distribution, city-wise breakdown, ROI estimates, brand recall benchmarks, and comparison to industry benchmarks.',
  },
  {
    category: 'Partners',
    question: 'How does the ZAP STAR partner program work?',
    answer: 'ZAP STAR is our retailer and agency partner network. Partners get co-branded campaigns, commission on referred clients, a dedicated support line, and access to our media rate cards. Apply via the ZAP STAR page.',
  },
]
